version: '3'

services:
  server:
    build:
      context: ./orquestador
    ports:
      - "5000:5000"
    networks:
      - app-network

  client:
    build:
      context: ./cliente
    networks:
      - app-network
    depends_on:
      - server
    environment:
      SERVER_URL: "https://server:5000"  # HTTPS

networks:
  app-network:
    driver: bridge
