# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0c\x41uthResponse\x12\r\n\x05token\x18\x01 \x01(\t\"D\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"\"\n\x10RegisterResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\"\n\x12\x43reationVPNRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x13\x43reationVPNResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\x31\n\x07Greeter\x12&\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply2k\n\x0b\x41uthService\x12+\n\x0c\x41uthenticate\x12\x0c.AuthRequest\x1a\r.AuthResponse\x12/\n\x08Register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse2D\n\nVPNService\x12\x36\n\tcreateVPN\x12\x13.CreationVPNRequest\x1a\x14.CreationVPNResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=14
  _globals['_HELLOREQUEST']._serialized_end=42
  _globals['_HELLOREPLY']._serialized_start=44
  _globals['_HELLOREPLY']._serialized_end=73
  _globals['_AUTHREQUEST']._serialized_start=75
  _globals['_AUTHREQUEST']._serialized_end=124
  _globals['_AUTHRESPONSE']._serialized_start=126
  _globals['_AUTHRESPONSE']._serialized_end=155
  _globals['_REGISTERREQUEST']._serialized_start=157
  _globals['_REGISTERREQUEST']._serialized_end=225
  _globals['_REGISTERRESPONSE']._serialized_start=227
  _globals['_REGISTERRESPONSE']._serialized_end=261
  _globals['_CREATIONVPNREQUEST']._serialized_start=263
  _globals['_CREATIONVPNREQUEST']._serialized_end=297
  _globals['_CREATIONVPNRESPONSE']._serialized_start=299
  _globals['_CREATIONVPNRESPONSE']._serialized_end=336
  _globals['_GREETER']._serialized_start=338
  _globals['_GREETER']._serialized_end=387
  _globals['_AUTHSERVICE']._serialized_start=389
  _globals['_AUTHSERVICE']._serialized_end=496
  _globals['_VPNSERVICE']._serialized_start=498
  _globals['_VPNSERVICE']._serialized_end=566
# @@protoc_insertion_point(module_scope)
