syntax = "proto3";

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply);
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}


service AuthService {
  rpc Authenticate (AuthRequest) returns (AuthResponse);
  rpc Register (RegisterRequest) returns (RegisterResponse);
}
message AuthRequest {
  string username = 1;
  string password = 2;
}
message AuthResponse {
  string token = 1;
}
message RegisterRequest {
    string username = 1;
    string email = 2;
    string pass = 3;
}
message RegisterResponse {
    bool result = 1;
}



service VPNService {
  rpc createVPN(CreationVPNRequest) returns (CreationVPNResponse);
}

message CreationVPNRequest {
  string name = 1;
}

message CreationVPNResponse {
  bool result = 1;
}