# Crear una imagen de debian 
FROM debian:latest

# Instalar git
RUN apt-get update && apt-get install -y git

# Instalar python3
RUN apt-get install -y python3

# Instalar wireguard
RUN apt-get install -y wireguard

